import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Website-Einstellungen",
  type: "document",
  groups: [
    { name: "betrieb", title: "Betrieb", default: true },
    { name: "navigation", title: "Navigation & Fusszeile" },
    { name: "seo", title: "Suchmaschinen" },
    { name: "recht", title: "Cookie-Hinweis" },
  ],
  fields: [
    defineField({
      name: "firmenname",
      title: "Firmenname",
      type: "string",
      group: "betrieb",
      description: "Voller Name, z. B. für Impressum und Seitentitel.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "kurzname",
      title: "Kurzname",
      type: "string",
      group: "betrieb",
      description: "Erscheint neben dem Logo in der Kopfzeile.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "claim",
      title: "Leitsatz",
      type: "string",
      group: "betrieb",
      description: "Ein kurzer Satz unter dem Namen, z. B. «Familienbetrieb seit Generationen».",
    }),
    defineField({
      name: "logo",
      title: "Logo",
      type: "image",
      group: "betrieb",
      description: "PNG mit transparentem Hintergrund, mindestens 320 × 320 Pixel.",
      fields: [{ name: "alt", title: "Bildbeschreibung", type: "string", description: "Wird vorgelesen, wenn das Bild nicht sichtbar ist." }],
    }),
    defineField({
      name: "telefon",
      title: "Haupt-Telefonnummer",
      type: "string",
      group: "betrieb",
      description: "So, wie sie angezeigt werden soll, z. B. 044 381 47 17.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "email",
      title: "Haupt-E-Mail",
      type: "string",
      group: "betrieb",
      validation: (r) => r.required().email(),
    }),
    defineField({
      name: "navigation",
      title: "Hauptnavigation",
      type: "array",
      group: "navigation",
      description: "Reihenfolge per Ziehen ändern. Empfohlen: höchstens 5 Einträge.",
      of: [
        {
          type: "object",
          name: "navEintrag",
          title: "Menüpunkt",
          fields: [
            defineField({ name: "label", title: "Beschriftung", type: "string", validation: (r) => r.required() }),
            defineField({
              name: "seite",
              title: "Seite",
              type: "reference",
              to: [{ type: "seite" }],
              validation: (r) => r.required(),
            }),
          ],
          preview: { select: { title: "label", subtitle: "seite.titel" } },
        },
      ],
      validation: (r) => r.max(6).warning("Mehr als 6 Menüpunkte passen auf dem Handy schlecht."),
    }),
    defineField({
      name: "footerLinks",
      title: "Links in der Fusszeile",
      type: "array",
      group: "navigation",
      description: "Z. B. Impressum und Datenschutz.",
      of: [
        {
          type: "object",
          name: "footerLink",
          title: "Link",
          fields: [
            defineField({ name: "label", title: "Beschriftung", type: "string", validation: (r) => r.required() }),
            defineField({ name: "seite", title: "Seite", type: "reference", to: [{ type: "seite" }], validation: (r) => r.required() }),
          ],
          preview: { select: { title: "label", subtitle: "seite.titel" } },
        },
      ],
    }),
    defineField({
      name: "footerText",
      title: "Text in der Fusszeile",
      type: "text",
      rows: 2,
      group: "navigation",
      description: "Kurzer Satz, z. B. ein Hinweis auf die Werkstätten.",
    }),
    defineField({
      name: "seoTitelZusatz",
      title: "Zusatz im Browser-Titel",
      type: "string",
      group: "seo",
      description: "Wird jedem Seitentitel angehängt, z. B. «Garage Klausner Zürich».",
    }),
    defineField({
      name: "seoBeschreibung",
      title: "Standard-Beschreibung",
      type: "text",
      rows: 3,
      group: "seo",
      description: "Erscheint in Suchergebnissen, wenn eine Seite keine eigene Beschreibung hat. Maximal 160 Zeichen.",
      validation: (r) => r.max(160).warning("Google kürzt Beschreibungen über 160 Zeichen."),
    }),
    defineField({
      name: "cookieHinweisAnzeigen",
      title: "Cookie-Hinweis anzeigen",
      type: "boolean",
      group: "recht",
      description: "Zeigt beim ersten Besuch eine Leiste am unteren Rand. Die Website setzt selbst keine Tracking-Cookies – der Hinweis informiert nur.",
      initialValue: true,
    }),
    defineField({
      name: "cookieHinweisText",
      title: "Text des Hinweises",
      type: "text",
      rows: 3,
      group: "recht",
      description: "Kurz und ehrlich. Der Link zur Datenschutzerklärung wird automatisch angehängt.",
      initialValue: "Diese Website verwendet keine Cookies zur Nachverfolgung und keine Analysedienste. Es werden nur technisch notwendige Daten verarbeitet.",
      validation: (r) => r.max(300),
    }),
    defineField({
      name: "cookieHinweisButton",
      title: "Beschriftung der Schaltfläche",
      type: "string",
      group: "recht",
      initialValue: "Verstanden",
      validation: (r) => r.max(30),
    }),
    defineField({
      name: "demoModus",
      title: "Demo-Modus (nicht von Suchmaschinen aufnehmen)",
      type: "boolean",
      group: "seo",
      description: "Eingeschaltet, solange die Website nur eine Vorschau ist. Vor dem Umzug auf die eigene Domain ausschalten.",
      initialValue: true,
    }),
  ],
  preview: { prepare: () => ({ title: "Website-Einstellungen" }) },
});
